# Generated by Django 5.1.5 on 2025-01-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('phone', models.IntegerField(max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'phone'), name='unique_email_pnone')],
            },
        ),
        migrations.CreateModel(
            name='RegisterPereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'На проверке'), ('accepted', 'Проверка пройдена'), ('rejected', 'Проверка пройдена, информация не принята')], db_index=True, default='new', max_length=10)),
                ('beauty_title', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('other_titles', models.CharField(max_length=50)),
                ('connect', models.DateTimeField(auto_now=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvl.userregister')),
            ],
        ),
    ]
