# Generated by Django 5.1.5 on 2025-02-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer', models.CharField(choices=[('1A', '1а'), ('1B', '1б'), ('2A', '2а'), ('2B', '2б'), ('3A', '3а'), ('3B', '3б'), ('3B*', '3б*')], default='1A', max_length=10)),
                ('autumn', models.CharField(choices=[('1A', '1а'), ('1B', '1б'), ('2A', '2а'), ('2B', '2б'), ('3A', '3а'), ('3B', '3б'), ('3B*', '3б*')], default='1A', max_length=10)),
                ('winter', models.CharField(choices=[('1A', '1а'), ('1B', '1б'), ('2A', '2а'), ('2B', '2б'), ('3A', '3а'), ('3B', '3б'), ('3B*', '3б*')], default='1A', max_length=10)),
                ('spring', models.CharField(choices=[('1A', '1а'), ('1B', '1б'), ('2A', '2а'), ('2B', '2б'), ('3A', '3а'), ('3B', '3б'), ('3B*', '3б*')], default='1A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('otc', models.CharField(max_length=100)),
                ('fam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perevals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'В работе'), ('accepted', 'Принято'), ('rejected', 'Отколонено')], db_index=True, default='new', max_length=10)),
                ('beauty_title', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('other_titles', models.CharField(blank=True, max_length=50)),
                ('connect', models.DateTimeField(auto_now=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prvl.coords')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prvl.levels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prvl.users')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pereval_images_image', to='prvl.perevals')),
                ('pereval', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pereval_images_pereval', to='prvl.perevals')),
            ],
        ),
    ]
