# Generated by Django 5.1.5 on 2025-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvl', '0002_alter_perevals_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevals',
            name='beauty_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perevals',
            name='other_titles',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perevals',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
